---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL
resolutions:
  rule_violations:
    - message: "No license information is available for dependency 'PyPI::httpx:0.26.0'."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The dependency has BSD 3-Clause license in github repo"
    - message: "The declared license 'BSD License' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package PyPI::httpx:0.26.0."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The dependency has BSD 3-Clause license in github repo"

    - message: "No license information is available for dependency 'PyPI::aiocache:0.12.2'."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The dependency has BSD 3-Clause license in github repo"

    - message: "No license information is available for dependency 'PyPI::httpcore:1.0.2'."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The dependency has BSD 3-Clause license in github repo"
    - message: "The declared license 'BSD License' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package PyPI::httpcore:1.0.2."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The dependency has BSD 3-Clause license in github repo"
