---
excludes:
  scopes:
  - pattern: "dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  - pattern: "lint"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for static code analysis only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
